### 체험 리스트 조회(offset)
GET https://sp-globalnomad-api.vercel.app/4-14/activities?method=offset

### 체험 이미지 url 생성
POST https://sp-globalnomad-api.vercel.app/4-14/activities/images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzA1LCJ0ZWFtSWQiOiI0LTE0IiwiaWF0IjoxNzE2Nzk3MzQxLCJleHAiOjE3MTY3OTkxNDEsImlzcyI6InNwLWdsb2JhbG5vbWFkIn0.am2_Hb_9yxoorVkJPGPbQAKtLRgfliHtUCiQJOqcDxc
Content-Type: multipart/form-data

{
  "image" : ""
}
